# ██████╗ ███████╗           ██╗██╗    ██╗      █████╗ ███╗   ██╗██████╗ 
# ╚════██╗██╔════╝           ██║██║    ██║     ██╔══██╗████╗  ██║██╔══██╗
#  █████╔╝███████╗█████╗     ██║██║    ██║     ███████║██╔██╗ ██║██║  ██║
# ██╔═══╝ ╚════██║╚════╝██   ██║██║    ██║     ██╔══██║██║╚██╗██║██║  ██║
# ███████╗███████║      ╚█████╔╝██║    ███████╗██║  ██║██║ ╚████║██████╔╝
# ╚══════╝╚══════╝       ╚════╝ ╚═╝    ╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ 

# -----------------------------------------------------
# MONITOR & PROGRAMS
# -----------------------------------------------------
source = ~/.config/hypr/modules/monitors.conf
source = ~/.config/hypr/modules/programs.conf

# -----------------------------------------------------
# AUTOSTART & ENV
# -----------------------------------------------------
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/env.conf

# -----------------------------------------------------
# LOOK AND FEEL
# -----------------------------------------------------
source = ~/.config/hypr/modules/general.conf
source = ~/.config/hypr/modules/animations.conf
source = ~/.config/hypr/theme.conf

# -----------------------------------------------------
# INPUT & KEYBINDINGS
# -----------------------------------------------------
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/keybindings.conf

# -----------------------------------------------------
# WINDOWS & WORKSPACES
# -----------------------------------------------------
source = ~/.config/hypr/modules/windowrules.conf