import os
import shutil
from src import ASSETS_PATH
from src.utils.execute import execute_as_root
from pathlib import Path
from typing import List, Dict

THEME_NAME = 'nigo'
ICON_NAME = 'white'
THEME_DIR_BASE: Path = Path('/usr/share/grub/themes')
GRUB_CONFIG_FILE: Path = Path('/etc/default/grub')
GRUB_ASSETS_DIR = ASSETS_PATH / 'grub'
WALLPAPER = GRUB_ASSETS_DIR / 'background.jpg'
RESOLUTION = '1080p'
GFX_MODES = {
    '1080p': '1920x1080', '2k': '2560x1440', '4k': '3840x2160',
    'ultrawide': '2560x1080', 'ultrawide2k': '3440x1440'
}

def get_asset_resolution(screen_variant: str) -> str:
    if screen_variant in ['ultrawide', '1080p']:
        return '1080p'
    if screen_variant in ['ultrawide2k', '2k']:
        return '2k'
    if screen_variant == '4k':
        return '4k'
    try:
        width = int(screen_variant.split('x')[0])
        if width <= 1920:
            return '1080p'
        elif width <= 2560:
            return '2k'
        else:
            return '4k'
    except (ValueError, IndexError):
        return '1080p'

def apply_grub_theme() -> None:
    dest_theme_path = THEME_DIR_BASE / THEME_NAME
    if dest_theme_path.exists():
        shutil.rmtree(dest_theme_path)
    os.makedirs(dest_theme_path, exist_ok=True)
    asset_res = get_asset_resolution(RESOLUTION)
    shutil.copytree(GRUB_ASSETS_DIR / 'common', dest_theme_path, dirs_exist_ok=True)
    theme_config_file = f'theme-{RESOLUTION if RESOLUTION in ['1080p', '2k', '4k', 'ultrawide', 'ultrawide2k'] else asset_res}.txt'
    shutil.copy(GRUB_ASSETS_DIR / 'config' / theme_config_file, dest_theme_path / 'theme.txt')
    shutil.copy(WALLPAPER, dest_theme_path / 'background.jpg')
    shutil.copytree(GRUB_ASSETS_DIR / 'assets' / f'assets-{ICON_NAME}' / f'icons-{asset_res}', dest_theme_path / 'icons')
    shutil.copytree(GRUB_ASSETS_DIR / 'assets' / 'assets-select' / f'select-{asset_res}', dest_theme_path, dirs_exist_ok=True)
    shutil.copy(GRUB_ASSETS_DIR / 'assets' / f'info-{asset_res}.png', dest_theme_path / 'info.png')

    if GRUB_CONFIG_FILE.exists():
        shutil.copy(GRUB_CONFIG_FILE, f'{GRUB_CONFIG_FILE}.bak')
    else:
        with open(GRUB_CONFIG_FILE, 'w') as f:
            f.write('# Generated by nigolinux-v2\n')
    with open(GRUB_CONFIG_FILE, 'r') as f:
        lines: List[str] = f.readlines()
    gfx_mode_value = GFX_MODES.get(RESOLUTION, RESOLUTION)
    theme_path = THEME_DIR_BASE / THEME_NAME / 'theme.txt'
    configs_to_set = {
        'GRUB_THEME': f'GRUB_THEME="{theme_path}"',
        'GRUB_GFXMODE': f'GRUB_GFXMODE={gfx_mode_value},auto'
    }
    new_lines: List[str] = []
    found_keys: Dict[str, bool] = {key: False for key in configs_to_set}
    for line in lines:
        stripped_line: str = line.strip()
        updated: bool = False
        for key, value in configs_to_set.items():
            if stripped_line.startswith(key + '=') or stripped_line.startswith('#' + key + '='):
                new_lines.append(value + '\n')
                found_keys[key] = True
                updated = True
                break
        if not updated:
            new_lines.append(line)
    for key, found in found_keys.items():
        if not found:
            new_lines.append(configs_to_set[key] + '\n')
    with open(GRUB_CONFIG_FILE, 'w') as f:
        f.writelines(new_lines)
    
    commands_to_try = [
        ['update-grub'],
        ['grub-mkconfig', '-o', '/boot/grub/grub.cfg'],
        ['grub2-mkconfig', '-o', '/boot/grub2/grub.cfg'],
    ]
    for command in commands_to_try:
        if shutil.which(command[0]) is None:
            continue
        try:
            execute_as_root(command)
            return
        except Exception:
            continue